<a href="https://colab.research.google.com/github/Wenjie0o0/ClassAI/blob/main/class02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
# grad = True
tensor = torch.rand(3, requires_grad=True)
print(tensor)
y = tensor + 6
print(y)
z = 3*y**2 + 2
print(z)
z = z.mean()
print(z)
z.backward() # dz/d(tensor)
print(tensor.grad) # 2*tensor + 12

tensor([0.9013, 0.8869, 0.0431], requires_grad=True)
tensor([6.9013, 6.8869, 6.0431], grad_fn=<AddBackward0>)
tensor([144.8849, 144.2887, 111.5558], grad_fn=<AddBackward0>)
tensor(133.5765, grad_fn=<MeanBackward0>)
tensor([13.8027, 13.7738, 12.0861])


In [5]:
#toy example
x=torch.tensor([[1,-1],[2,3],[5,2]],dtype=torch.float32)
y=torch.tensor([[1],[0],[1]],dtype=torch.float32)

w1=torch.rand(2,3,requires_grad=True)
w2=torch.rand(3,3,requires_grad=True)
w3=torch.rand(3,2,requires_grad=True)
w4=torch.rand(2,1,requires_grad=True)
relu=nn.ReLU()
sigmod=nn.Sigmoid()
bce=nn.BCELoss()

def forward(inputs):
  inputs=torch.matmul(inputs,w1)
  inputs=relu(inputs)
  inputs=torch.matmul(inputs,w2)
  inputs=relu(inputs)
  inputs=torch.matmul(inputs,w3)
  inputs=relu(inputs)
  inputs=torch.matmul(inputs,w4)
  outputs=sigmod(inputs)
  return outputs

#loss
def loss(y_true,y_pred):
  return bce(y_pred,y_true)
learning_rate=0.01
epochs=10

for epoch in range(epochs):
  y_hat=forward(inputs=x)

  bce_loss=loss(y_true=y,y_pred=y_hat)
  bce_loss.backward()
  with torch.no_grad():
    w1-=learning_rate*w1.grad
    w2-=learning_rate*w2.grad
    w3-=learning_rate*w3.grad
    w4-=learning_rate*w4.grad

  w1.grad.zero_()
  w2.grad.zero_()
  w3.grad.zero_()
  w4.grad.zero_()
  if epoch % 5 == 0:
    print(f"epoch {epoch + 1}: \nw1 = {w1}\n w2 = {w2}\n w3 = {w3}\n w4 = {w4}, loss = {bce_loss:.8f}")

epoch 1: 
w1 = tensor([[0.3722, 0.2103, 0.8484],
        [0.2544, 0.8105, 0.8887]], requires_grad=True)
 w2 = tensor([[0.5339, 0.2370, 0.0421],
        [0.0281, 0.2062, 0.8816],
        [0.3940, 0.7964, 0.2946]], requires_grad=True)
 w3 = tensor([[0.4189, 0.5266],
        [0.1572, 0.4123],
        [0.7728, 0.5325]], requires_grad=True)
 w4 = tensor([[0.7007],
        [0.1097]], requires_grad=True), loss = 1.64672911
epoch 6: 
w1 = tensor([[0.3674, 0.1946, 0.8369],
        [0.2423, 0.7861, 0.8709]], requires_grad=True)
 w2 = tensor([[0.5269, 0.2342, 0.0299],
        [0.0141, 0.2007, 0.8572],
        [0.3727, 0.7879, 0.2573]], requires_grad=True)
 w3 = tensor([[0.3927, 0.5235],
        [0.1115, 0.4070],
        [0.7335, 0.5279]], requires_grad=True)
 w4 = tensor([[0.6312],
        [0.0305]], requires_grad=True), loss = 1.21439981


Dataset & DataLoader

In [6]:
from torch.utils.data import Dataset,DataLoader
class ScoreDataset(Dataset):
  def __init__(self):
      self.x=torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
      self.y=torch.tensor([[1],[0],[1],[1],[1],[0]])
  def __getitem__(self, index):
      return self.x[index],self.y[index]
  def __len__(self):
    return self.x.size(0)

In [7]:
score_dataset=ScoreDataset()

In [8]:
print(score_dataset.x)
print(score_dataset.y)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
tensor([[1],
        [0],
        [1],
        [1],
        [1],
        [0]])


In [10]:
dataloader=DataLoader(dataset=score_dataset,batch_size=2,shuffle=True)
for i, (x,y) in enumerate(dataloader):
  print(f"{i}: x={x}, y={y}")

0: x=tensor([[16, 17, 18],
        [ 7,  8,  9]]), y=tensor([[0],
        [1]])
1: x=tensor([[10, 11, 12],
        [ 1,  2,  3]]), y=tensor([[1],
        [1]])
2: x=tensor([[13, 14, 15],
        [ 4,  5,  6]]), y=tensor([[1],
        [0]])
