<a href="https://colab.research.google.com/github/Wenjie0o0/ClassAI/blob/main/class02_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import cv2

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
path='/content/drive/MyDrive/Colab Notebooks/cat.jpg'

In [6]:
image=cv2.imread(path)


In [7]:
print(type(image))
print(image.shape)
print(image)

<class 'numpy.ndarray'>
(5012, 6837, 3)
[[[163 190 217]
  [161 188 215]
  [162 189 216]
  ...
  [142 165 197]
  [142 165 197]
  [142 165 197]]

 [[162 189 216]
  [161 188 215]
  [162 189 216]
  ...
  [142 165 197]
  [142 165 197]
  [141 164 196]]

 [[162 189 216]
  [161 188 215]
  [161 188 215]
  ...
  [141 164 196]
  [141 164 196]
  [141 164 196]]

 ...

 [[186 186 186]
  [185 185 185]
  [184 184 184]
  ...
  [149 147 146]
  [151 149 148]
  [153 151 150]]

 [[187 187 187]
  [186 186 186]
  [185 185 185]
  ...
  [150 148 147]
  [151 149 148]
  [152 150 149]]

 [[187 187 187]
  [186 186 186]
  [185 185 185]
  ...
  [148 146 145]
  [148 146 145]
  [149 147 146]]]


In [8]:
plt.show(image)

NameError: ignored