<a href="https://colab.research.google.com/github/Wenjie0o0/AI2/blob/main/class01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np


In [ ]:
tensor = torch.rand(2,3)
matrix = np.random.rand(2,3)
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")


Tensor:
 tensor([[0.2261, 0.8253, 0.0729],
        [0.0944, 0.7260, 0.5187]])
Matrix:
 [[0.05265803 0.11641419 0.41684572]
 [0.05856795 0.30554844 0.16085572]]
